server {
    listen 80;
    server_name _;

    client_max_body_size 12m;

    location = /portal {
        return 301 /portal/;
    }

    location /api/v1/ {
        proxy_pass http://api:8080/api/v1/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 30s;
        proxy_send_timeout 220s;
        proxy_read_timeout 220s;
    }

    location /portal/ {
        alias /usr/share/nginx/html/portal/;
        try_files $uri $uri/ /portal/index.html;
    }

    location / {
        root /usr/share/nginx/html/knowledge;
        try_files $uri $uri/ /index.html;
    }
}
