package com.studyforge.admin.vo;

import java.time.LocalDate;
import java.time.LocalDateTime;

public record AdminUserDetailVO(Long userId,
                                String username,
                                String displayName,
                                String email,
                                String role,
                                String status,
                                String bio,
                                String avatarUrl,
                                String bannerUrl,
                                int communityLevel,
                                int experiencePoints,
                                LocalDate lastLoginRewardDate,
                                int reputationScore,
                                int postCount,
                                int publishedPostCount,
                                int archivedPostCount,
                                int commentCount,
                                int likeCount,
                                int favoriteCount,
                                int collectionCount,
                                int historyCount,
                                int followerCount,
                                int followingCount,
                                int friendCount,
                                int incomingFriendRequestCount,
                                int outgoingFriendRequestCount,
                                int sentMessageCount,
                                int receivedMessageCount,
                                int helpRequestCount,
                                int helpAnswerCount,
                                int acceptedAnswerCount,
                                int reportCount,
                                int reportedPostCount,
                                int uploadCount,
                                int aiCallCount,
                                int aiSuccessCount,
                                int voiceRecordCount,
                                int activeTokenCount,
                                int experienceLogCount,
                                LocalDateTime lastPostTime,
                                LocalDateTime lastCommentTime,
                                LocalDateTime lastHelpTime,
                                LocalDateTime lastAiCallTime,
                                LocalDateTime lastVoiceTime,
                                LocalDateTime createdTime,
                                LocalDateTime updatedTime) {
}
